#-------------------------------
# General Site Settings

title: My Portfolio
logo: 
author: themefisher
description: this is meta description
email: sakib.1490@gmail.com
phone: +1 319 400 9219
address: 605 Woodside Drive, Iowa City, Iowa, USA
copyright: Copyright &copy; 2022 Designed by [Themefisher](https://themefisher.com) & Developed by [Getjekyllthemes](https://getjekyllthemes.com)

menu:
- {name: About, link: '/about'}
- {name: Blog, link: '/blog'}
- {name: Portfolio, link: '/portfolio'}
- {name: Contact, link: '/contact'}


#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: # UA-XXXXXX-X


#-------------------------------
# Comment Section (Disqus)

disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Hero Section

hero:
  hero-title: Hi! I’m <br> Shakib <br> Materials Scientist

social:
- {icon: "ti-facebook", link: "#"}
- {icon: "ti-instagram", link: "#"}
- {icon: "ti-dribbble", link: "#"}
- {icon: "ti-twitter", link: "#"}
- {icon: "ti-linkedin", link: "https://www.linkedin.com/in/mahmudul-alam-shakib/"}


#-------------------------------
# About (Section and Page)

# About Section
blurb:
  I am a PhD Student at the University of Iowa, where I am a Gradaute Research Assistant in the Smart Multifunctional Material Systems Lab. My current research focus is smart materials and spatially tailored materials (nanocomposites). 

blurb-btn-link: '/about'
blurb-btn-name: know more


# About Page

# Work Process Section
work-process:
  - title : "Literature Review"
    icon : "assets/images/icons/plan.png"
    content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
    
  - title : "Experimentation, Modeling & Simulation"
    icon : "assets/images/icons/design.png"
    content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
    
  - title : "Publication"
    icon : "assets/images/icons/print.png"
    content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."


# My Team Section
#team:
 # - title : "Person 1"
#    image : "#"
 #   designation : "Project Manager"
    
 # - title : "Person 2"
 #   image : "#"
 #   designation : "Web Developer"
    
#  - title : "Person 3"
 #   image : "assets/images/team/.png"
 #   designation : "Designer"


#-------------------------------
# Skills Section

skills-title: Skills
skills:
- {name: Electrochemical Characterization, color: '#fdb157', value: '60%'}
- {name: Mechanical Characterization, color: '#9473e6', value: '90%'}
- {name: Atomic Force Microscopy, color: '#bdecf6', value: '60%'}
- {name: Nanomaterials Fabrication, color: '#9473e6', value: '70%'}
- {name: Nano DMA, color: '#ffbcaa', value: '50%'}
- {name: COMSOL Multiphysics, color: '#bdecf6', value: '40%'}

#-------------------------------
# Exprerience Section

experience-title: Experience
experience:
- {name: Graduate Research Assistant, icon: 'icon-2.png', date: 'Feb 2020 - Present', organization: '[University of Iowa](https://uiowa.edu/absolute-file.html)'}
- {name: Lecturer, icon: 'icon-1.png', date: 'Aug 2019 - Feb 2020', organization: 'European University of Bangladesh'}
- {name: Engineering Officer, icon: 'icon-3.png', date: 'Sep 2018 - Aug 2019', organization: 'Incepta Pharmaceuticals Ltd.'}


#-------------------------------
# Education Section

education-title: Education
education:
- {name: PhD in Mechanical Engineering, date: '2020-Present', organization: 'University of Iowa'}
- {name: BSc in Mechanical Engineering, date: '2017', organization: 'Islamic University of Technology'}
- {name: Higher Secondary Certificate, date: '2013', organization: 'Barishal Cadet College'}
- {name: Secondary School Certificate, date: '2011', organization: 'Barishal Cadet College'}


#-------------------------------
# Services Section

services-title: Projects
services:
- {
    name: Artificial Synapse with Ceramic Materials,
    icon: ti-palette,
    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    active: # Add true to select section
  }
- {
    name: Manufacturing and Characterization of STM,
    icon: ti-vector,
    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    active: true # Add true to select section
  }
- {
    name: Novel Piezoelectric Materials,
    icon: ti-panel,
    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    active: # Add true to select section
  }



#-------------------------------
# Portfolio (Section and Page)

# Portfolio Home Section
portfolio-home-items:
  - image : "assets/images/portfolio/item-1.png"
    url: "#"
    
  - image : "assets/images/portfolio/item-2.png"
    url: "#"
    
  - image : "assets/images/portfolio/item-3.png"
    url: "#"
    
  - image : "assets/images/portfolio/item-4.png"
    url: "#"
    
  - image : "assets/images/portfolio/item-5.png"
    url: "#"


# Portfolio Page
portfolio-label:
- {
    title : "UI/UX Design",
    type : "design"
  }
- {
    title : "BRANDING",
    type : "branding"
  }
- {
    title : "ILLUSTRATION",
    type : "illustration"
  }

portfolio-items:
  - image : "assets/images/portfolio/item-1.png"
    url: "#"
    portfolio-type:
     - type: "design"
     - type: "illustration"
      
  - image : "assets/images/portfolio/item-2.png"
    url: "#"
    portfolio-type:
      - type: "branding"
      
  - image : "assets/images/portfolio/item-3.png"
    url: "#"
    portfolio-type:
      - type: "illustration"
      
  - image : "assets/images/portfolio/item-6.png"
    url: "#"
    portfolio-type:
      - type: "design"
      - type: "branding"
      
  - image : "assets/images/portfolio/item-8.png"
    url: "#"
    portfolio-type:
      - type: "illustration"
      
  - image : "assets/images/portfolio/item-5.png"
    url: "#"
    portfolio-type:
      - type: "design"
      
  - image : "assets/images/portfolio/item-1.png"
    url: "#"
    portfolio-type:
      - type: "branding"
      
  - image : "assets/images/portfolio/item-3.png"
    url: "#"
    portfolio-type:
      - type: "design"
      - type: "illustration"
      - type: "branding"
      
  - image : "assets/images/portfolio/item-7.png"
    url: "#"
    portfolio-type:
      - type: "illustration"


#-------------------------------
# Testimonials Section

testimonial-items:
  - name: "Sayedus Salehin"
    image: "assets/images/testimonial/Salehin.jpg"
    designation : "Undergrad Thesis Supervisor"
    content : "I am pleased to write a recommendation for Mr. Shakib who was my direct student during his undergraduate studies. I taught and instructed him in couple of theory and lab courses and found him to be an intelligent individual who used to participate actively in the classes. He achieved the highest grade in all the courses that I have instructed depicting his deep understanding of the subject matters.

I also co-supervised him in his undergraduate final year thesis where he worked on evaluating the possibility of production of biodiesel from local and marine sourced micro-algae in Bangladesh. He has demonstrated empirical information on the production of biodiesel from two different species of microalgae. After collection, isolation, harvesting and production of aforesaid species of microalgae, he has extracted biodiesel from the dry biomass using Soxhlet extraction method. 

He possesses excellent communication and leadership skill which have been demonstrated by his role as the president of the university Mars Rover team and other organizing positions. I found him as a diligent, thorough and responsible individual who has a passion for research and ready to go the extra mile with his perseverance. 

I believe he will be an extremely positive asset to any institution. I wish him all the best in his future career. "
    
  - name: "Saad Mahmud Sonyy"
    image: "assets/images/testimonial/Sonyy.jpg"
    designation: "Colleague at Incepta"
    content: "The old adage of “Efficiency is doing the thing right. Effectiveness is doing the right thing.” is totally true when it comes to Mr. Mahmudul Alam Shakib. Mr. Shakib is a whirlwind of energy that simply just never stops; it's been three years since I know him after his joining in Incepta in the same department, and I've never seen another engineer who can demand total attention as quickly as him, and it's rare to come across raw talents that stand out like him. Being the in charge of a multifaceted setup isn’t always an easy task but Mr. Shakib made the process relatively smooth for everyone. His ability to decipher complicated problems and arrive at simple solutions was unrivalled. 
I've always been impressed by his resolve to get the bottom of every problem to eradicate them so effectively and so that they don't resurface, while yet allocating enough time to assist others. 
I had the pleasure of working with him on a number of projects, collaborating on several project teams; his ability to handle multiple projects with ease was unlike anything I'd ever seen before, and it significantly increased the overall workshop support and services capability to handle installation, commissioning, and fabrication related activities. Mr. Shakib even under huge work pressure gave everyone the vibe that everything is just normal and that everything is as it should be, while ensuring that everyone would leave with a smile. 
His extensive understanding of robotics, mechatronics, and automation enabled the team to extend its horizons, allowing them to delve further and approach the initial impediments with a rejuvenated outlook. Being a quick learner enabled him to comprehend the management's requirements, as well as come up with ways to solve problems and assist his teammates by bringing all of his skills and abilities to the table while sacrificing nothing in terms of creativity in effort to bring his team to perfection. 
His academic and industry knowledge, I strongly believe, will be pivotal in the rapid diversification and the expansion of any organization on a larger scale to a global footprint. He is a detail-oriented, well-organized, and resourceful individual. To say the least, he's a valuable resource. Mr. Shakib's excellent understanding of strategy and timing was profoundly beneficial, whether organizing a team effort on particular goals or ensuring that all units were regularly and thoroughly updated on their goals and as well as their achievements. 
Mr. Shakib is an excellent resource, and a master at real-life practical engineering problems & had been a real gem to our engineering department. He makes sure that all deadlines are met, and that they are met to the best possible standards; He is a sincere and hardworking individual who will complete any task within the stipulated timeframe. Mr. Shakib would be an excellent addition to any organization in need of a skilled mechanical engineer, and it is my pleasure and honor to recommend him."
    
  - name: "Md. Anwarul Hoque"
    image: "assets/images/testimonial/Anwar.jpg"
    designation: "Colleague at Incepta"
    content: "He is technically very sound. He has innovative ideas for project-based activities. He is very sincere in his duty and responsibility. The people who will be in touch with him during his professional career will be lucky as many opportunities will come to learn from him. He can devote himself to finding out the solution to any assigned task."


#-------------------------------
# Client Slider Section

client-slider-items:
  - logo: "assets/images/clients-logo/client-logo-1.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-2.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-3.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-4.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-5.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-1.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-2.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-3.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-4.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-5.png"
    url: "#"

#-------------------------------
# Contact Section

contact-title: Contact Info
contact-email: sakib.1490@gmail.com
